# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff9fb7f5e097b88acb6fbdd829fc837910fa0ec204a40d1735d50f557c3d22c2360ef41001b64a95887f2613da7ebc5eb90831bf1ee083943bd553409f3266b2

test:
  secret_key_base: 4cad2d9eaa6f519950a1a6528125adf6049418f2f30eb75bde6e78c89f39e48eb93183ebc3a3cdc8dab7a256f757377a713ec9e42e2782cfe39744c8b2106e9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
